### PR TITLE
Draft: Partial indexes support

### PR DESCRIPTION
**Pull request by sywesk**
This Pull Request fixes issue #1472 .

### CODE REVIEW

**Comment by sywesk** [comment]
I'm having a bit of trouble to test the whole thing. I've implemented the indexbuilder method for the where clause, and updated the migrate code to take in account where clause changes, but i find it difficult to know where to put some tests. I've been looking at the `"add and remove indexes"` sub test in `dialect/sql/schema/postgres_test.go` . It feels like the right place to do so, but i'm not comfortable modifying it. Can one of you give me a little clue about how they work ?

**Comment by a8m** [comment]
Hey @sywesk, any update regarding this PR?

**Comment by einat24** [comment]
Hey @sywesk, wondered if you are planning to continue the work on this PR :)

**Comment by sywesk** [comment]
@einat24 sadly i don't think so :/ i needed a bit too much help to do it in a reasonable amount of time, this project is nothing short of complex.

**Pull request closed without merging**
