### PR TITLE
chore: use error.New when error without format

### PR DESCRIPTION
**Pull request by sashamelentyev**

### CODE REVIEW

**Comment by sashamelentyev** [comment]
@a8m, help please. 
I make go generate locally and have no changes, but CI is red

**Comment by a8m** [comment]
Thanks for the contribution @sashamelentyev 🙏 

Please, make sure you're rebased on origin/master and then run `go generate ./...`.

**Comment by sashamelentyev** [comment]
@a8m, thanks!

**Comment by a8m** [comment]
💯

**Review by a8m — APPROVED** [review]

**Pull request merged**
