### PR TITLE
Link to non-foreign-key join-table fields GH issue

### PR DESCRIPTION
**Pull request by bbkane**
https://github.com/ent/ent/issues/1061 seems to be a common question ( also see [Slack](https://gophers.slack.com/archives/C01FMSQDT53/p1630519196046300), so link to it in the docs.

### CODE REVIEW

**Comment by bbkane** [comment]
This PR is 9 days old now. Is there anything I need to change on it?

**Review by masseelch — APPROVED** [review]
LGTM

**Comment by a8m** [comment]
Hey @bbkane and sorry for the delay, I forgot to review this PR (holiday season in TLV) 🙏 

Thanks @masseelch for the review ❤️

**Comment by bbkane** [comment]
Thank you!!! Hope the holidays were great!
Ben

**Pull request merged**
