### PR TITLE
Add Chinese doc

### PR DESCRIPTION
**Pull request by yunteng9345**
Add Chinese dock

### CODE REVIEW

**Comment by a8m** [comment]
Hey @yunteng9345 and thanks for working on this.

We should check how we can enable this option in the website using [Docusaurus translation configuration](https://docusaurus.io/docs/en/translation#:~:text=Docusaurus%20allows%20for%20useful%20translation,in%20a%20tag). See an example in Docusaurus website:




cc @rotemtam

**Comment by yunteng9345** [comment]
> Hey @yunteng9345 and thanks for working on this.
> 
> We should check how we can enable this option in the website using [Docusaurus translation configuration](https://docusaurus.io/docs/en/translation#:~:text=Docusaurus%20allows%20for%20useful%20translation,in%20a%20tag). See an example in Docusaurus website:
> 
> 
> 
> cc @rotemtam

But I think the technical documents translated by translation tools are not accurate enough...

**Comment by uta-mori** [comment]
I think it would be better to support multiple languages after doc site move to docusaurus v2.

**Comment by a8m** [comment]
> But I think the technical documents translated by translation tools are not accurate enough...

We need to find a solution for it. Maybe some hybrid solution that can combine both Crowdin and our translation content. Something like [kubernetes/website](https://github.com/kubernetes/website/tree/master/content) with [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) and a dedicate team for each language.   

Like I commented in #1322, I plan to start working on it next week.

**Comment by yunteng9345** [comment]
> > But I think the technical documents translated by translation tools are not accurate enough...
> 
> We need to find a solution for it. Maybe some hybrid solution that can combine both Crowdin and our translation content. Something like [kubernetes/website](https://github.com/kubernetes/website/tree/master/content) with [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) and a dedicate team for each language.
> 
> Like I commented in #1322, I plan to start working on it next week.

That's a good plan！

**Comment by yunteng9345** [comment]
> > But I think the technical documents translated by translation tools are not accurate enough...
> 
> We need to find a solution for it. Maybe some hybrid solution that can combine both Crowdin and our translation content. Something like [kubernetes/website](https://github.com/kubernetes/website/tree/master/content) with [CODEOWNERS](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners) and a dedicate team for each language.
> 
> Like I commented in #1322, I plan to start working on it next week.

I want to contribute code to ENT, but I don't feel like I can do it. Do you have any good ideas?Do projects  or read the source code?

**Comment by a8m** [comment]
> I want to contribute code to ENT, but I don't feel like I can do it. Do you have any good ideas?Do projects or read the source code?

Hey @yunteng9345, please join the [Ent's channel](https://app.slack.com/client/T029RQSE6/C01FMSQDT53) on Slack and ping me there privately. I can help you to find some tasks to start with them.

**Comment by rotemtam** [comment]
@yunteng9345 we have enabled an integration with crowdin, as you can read [here](https://entgo.io/docs/translations/).
Closing this PR

**Pull request closed without merging**
