### PR TITLE
update go doc to match the method name

### PR DESCRIPTION
**Pull request by cpanato**
- update go doc to match the method name

### CODE REVIEW

**Comment by nabokihms** [comment]
@a8m this is a small change. Could you please take a like when you have time?

**Comment by a8m** [comment]
Thanks for the contribution. Please run codegen in both entc/integration and examples directories 🙏🏻

**Comment by cpanato** [comment]
thanks for the review, ran the codegen PTAL @a8m @nabokihms

**Comment by cpanato** [comment]
updated the codegen again, looks like was missing some files :/

**Comment by cpanato** [comment]
all green now :)

**Review by a8m — APPROVED** [review]
Thanks for the contribution, @cpanato.

**Pull request merged**
