### PR TITLE
Fix: Append UNION before ORDER BY

### LINKED ISSUE #1754: Specifying ORDER BY with UNION results in an sql syntax error
- [ ] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/ent/ent/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When doing `sql.Select().From(tableA).Union(tableB).OrderBy()` the `ORDER BY` clause is appended to `tableA`'s select instead of on the entire union (at the end of the SQL query).

## Expected Behavior 🤔

`OrderBy()` should be applied on the entire union.

## Steps to Reproduce 🕹

Steps:

1. Place into `dialect/sql/builder_test.go`:
```
func TestSelector_UnionOrderBy(t *testing.T) {
	table := Table("users")
	query, _ := Dialect(dialect.Postgres).
		Select("*").
		From(table).
		Where(EQ("active", true)).
		Union(Select("*").From(Table("old_users1"))).
		OrderBy(table.C("whatever")).
		Query()
	require.Equal(t, `SELECT * FROM "users" WHERE "active" = $1 UNION SELECT * FROM "old_users1" ORDER BY "users"."whatever"`, query)
}
```
2. go test -run TestSelector_UnionOrderBy

## Your Environment 🌎

| Tech        | Version |
| ----------- | ------- |
| Go          |  1.16.5  |
| Ent         | v0.8.1-0.20210719122135-201c7301aa86   |
| Database    | PostgreSQL   |
| Driver      | github.com/jackc/pgx/v4/stdlib        |

### PR DESCRIPTION
**Pull request by squarebat**
As reported in issue #1754 , specifying ORDER BY with union results in syntax error as ORDER BY wrongly gets appended before UNION. This PR fixes that by modifying the builder to append UNION before ORDER BY.
- Resolves #1754

### CODE REVIEW

**Comment by a8m** [comment]
Thanks for your contribution @squarebat, it's really appreciated! 🙏

**Comment by a8m** [comment]
@squarebat, can you please run gofmt on this file? (lint job is failing).

**Comment by squarebat** [comment]
@a8m Sure thing, will look into it.

**Comment by a8m** [comment]
@all-contributors, please add @squarebat for code.

**Comment by a8m** [comment]
@all-contributors please add @squarebat as a contributor for code

**Pull request merged**
