### PR TITLE
Add a Japanese version of README.md

### PR DESCRIPTION
**Pull request by 8ayac**
I've added a Japanese version of the README.

### CODE REVIEW

**Comment by a8m** [comment]
Thanks for the contribution @8ayac. 

@uta-mori, any chance to get your help here? Thanks 🙏

**Review by uta-mori — APPROVED** [review]
Looks good to me !

**Comment by a8m** [comment]
Thanks for your contribution @8ayac 🙏

**Comment by a8m** [comment]
And of course, thanks @uta-mori for the review. 

@all-contributors please add @8ayac for docs

@all-contributors please add @uta-mori for review

**Comment by a8m** [comment]
@all-contributors please add @8ayac for docs

**Comment by a8m** [comment]
@all-contributors please add @uta-mori for review

**Pull request merged**
