### PR TITLE
go: update go to latest

### PR DESCRIPTION
**Pull request by luantranminh**

### CODE REVIEW

**Review by a8m — APPROVED** [review]
💯

**Comment by a8m** [comment]
Thanks @luantranminh 🚀

**Comment by FZambia** [comment]
Hello @a8m , was there any specific motivation to do this? This stops Go programs that use Go 1.22  to depend on Ent:

```
go: entgo.io/ent@v0.14.1 requires go >= 1.23.0 (running go 1.22.6)
```

**Comment by godcong** [comment]
@FZambia I have the same question.

**Comment by jay-youngn** [comment]
@FZambia @godcong 

This is a popular project with 15.4k stars.
Interestingly. Breaking changes like this, **`No description provided` and Merged**.
What's more. Project maintainers are thanks for this behavior. 🤣

**Comment by a8m** [comment]
Supporting v1.23 requires updating go-tools (x/tools) package, which requires updating the Go version here.  Users that can't update their Go version, can stay on [v0.14.0](https://github.com/ent/ent/releases/tag/v0.14.0).

**Comment by godcong** [comment]
I'll give my opinion.
1. When testing, I think ci should turn off the toolchain to test `ent`'s flow under that version.
If toolchain is not closed, all tests will be upgraded to the specified version, which doesn't make much sense.
2. Hopefully `ent` can support 2 ~ 3 minor version compatibility. E.g. 1.21 ~ 1.23, because not everyone, all projects always use the latest version of go.
3. If I update a package (using: go get -u . /...) . . he will force me to update my go version. By the same token, this will force all the projects that use my project to update their go version. This is a very far-reaching effect!



I hope the project team will consider these implications later... I've now been updated to 1.23.1.

**Comment by jay-youngn** [comment]
> I'll give my opinion.
> 
> 1. When testing, I think ci should turn off the toolchain to test `ent`'s flow under that version.
>    If toolchain is not closed, all tests will be upgraded to the specified version, which doesn't make much sense.
> 2. Hopefully `ent` can support 2 ~ 3 minor version compatibility. E.g. 1.21 ~ 1.23, because not everyone, all projects always use the latest version of go.
> 3. If I update a package (using: go get -u . /...) . . he will force me to update my go version. By the same token, this will force all the projects that use my project to update their go version. This is a very far-reaching effect!
>    
> 
> I hope the project team will consider these implications later... I've now been updated to 1.23.1.

Agree,
This PR is just to fix version issues encountered by related projects and should not be merged in my opinion. 
(The result is more project version issues, It's a very selfish act.)

As a general library, every modification needs to be considered by a more professional person.
If someone reports my comment again, it will also confirm what I said.

This will not affect me in any way, but will highlight your guilt and stupidity.

**Comment by FZambia** [comment]
> Supporting v1.23 requires updating go-tools (x/tools) package, which requires updating the Go version here.

I am not sure I understand - the version of `x/tools` used by Ent now requires go1.19 https://cs.opensource.google/go/x/tools/+/refs/tags/v0.24.0:go.mod;l=3, and it would be very strange if `x/tools` required Go1.23 – because there are tons of projects which depend on it and I believe it follows Go convention to support at least 2 last minor Go versions (1.23 and 1.22 at this point).

**Comment by GuillotineOfJews** [comment]
> > Supporting v1.23 requires updating go-tools (x/tools) package, which requires updating the Go version here.
> 
> I am not sure I understand - the version of `x/tools` used by Ent now requires go1.19 https://cs.opensource.google/go/x/tools/+/refs/tags/v0.24.0:go.mod;l=3, and it would be very strange if `x/tools` required Go1.23 – because there are tons of projects which depend on it and I believe it follows Go convention to support at least 2 last minor Go versions (1.23 and 1.22 at this point).

### Yes, precisely, the version of `x/tools` utilized by `ent/ent` currently requires go1.19

Can anyone explain the conflict here?

It seems there are certain folks who are super amateurish and are just spouting random explanations, really ticking off the other guy.

**Comment by a8m** [comment]
Thanks for the feedback, @FZambia.

Apologies, my previous comment was inaccurate. One limitation we currently have between Ent/Atlas is that both projects depend on each other (creating a circular dependency). We're currently working on addressing this, but unfortunately, upgrading one project triggers an upgrade for the other.

As I mentioned above, I tagged version 0.14.0 before bumping to 0.14.1, and there are ~no differences between the two, aside from a few documentation changes. I apologize for any inconvenience - I'll check if there's a way to revert this or at least prevent this in the future. 

Unfortunately, this discussion has been the first and only instance of such an unpleasant engagement in the Ent community. While feedback is always welcome, it must remain constructive and free of abusive language - I'm locking this thread, but you're welcome to join our Discord if you'd like to continue the discussion or need any support.

---

@godcong - I appreciate your feedback as well, and your overall contribution for our community.

**Pull request merged**
