### PR TITLE
Add readonly client

### PR DESCRIPTION
**Pull request by cliedeman**
Allow the user to create a readonly version of the client that can only perform `Query` and `Get` operations

Transactions still need to be handled

Motviation:
I would to convery extra intent in differnet parts of the application by using a readonly client. E.g. in graphql resolvers there should only be reads.

### CODE REVIEW

**Comment by a8m** [comment]
Hey @cliedeman and thanks for creating this PR. For a read-only mode, I suggest users https://github.com/ent/ent/issues/1460#issuecomment-820614860, or to use a custom template, same as I used in my projects:

```go
{{ define "readonly" }}
{{ template "header" $ }}

// ReadOnly returns a new readonly client.
//
//	client := client.ReadOnly()
//
func (c *Client) ReadOnly() *Client {
	cfg := config{driver: &readonly{Driver: c.driver}, log: c.log}
	return &Client{
		config: cfg,
		{{- if $.SupportMigrate }}
			Schema: migrate.NewSchema(cfg.driver),
		{{- end }}
		{{ range $_, $n := $.Nodes -}}
			{{ $n.Name }}: New{{ $n.Name }}Client(cfg),
		{{ end -}}
	}
}

// ErrReadOnly returns when a read-only user tries to execute a write operation.
var ErrReadOnly = &PermissionError{cause: "permission denied: read-only user"}

// PermissionError represents a permission denied error.
type PermissionError struct {
	cause string
}

func (e PermissionError) Error() string { return e.cause }

type readonly struct {
	dialect.Driver
}

func (r *readonly) Exec(context.Context, string, interface{}, interface{}) error {
	return ErrReadOnly
}

func (r *readonly) Tx(context.Context) (dialect.Tx, error) {
	return nil, ErrReadOnly
}
{{ end }}
```

**Comment by a8m** [comment]
To be honest, I'd rather add it to the FAQ/examples as a referenced implementation, than add it to the core of the framework ❤️

**Comment by cliedeman** [comment]
@a8m no problem. I will try the external template. 

The example above won't work for me because I want a compile time failure instead of runtime. 

Can this be added to contrib or a similar repo? FAQ and examples are ok but they won't have CI or stay up to date. 

Ciaran

**Comment by cliedeman** [comment]
@a8m thanks for the pointers. I managed to combine the 2 approaches and I am quite happy with the result.

**Pull request closed without merging**
